CREATE TABLE IF NOT EXISTS device (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    ip INET NOT NULL,
    mac MACADDR NOT NULL,
    description TEXT,
    employee VARCHAR(3)
);
